---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-giphy-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jpunter/random-giphy.git
    targetRevision: HEAD
    path: deployment/overlays/prod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-giphy-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jpunter/random-giphy.git
    targetRevision: HEAD
    path: deployment/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
